# Python 数据类型

变量是存储在内存中的值，这就意味着在创建变量时会在内存中开辟一个空间。

基于变量的数据类型，解释器会分配指定内存，并决定什么数据可以被存储在内存中。

因此，变量可以指定不同的数据类型，这些变量可以存储整数，小数或字符。

### 变量赋值

Python 中的变量赋值不需要类型声明。

每个变量在内存中创建，都包括变量的标识，名称和数据这些信息。

每个变量在使用前都必须赋值，变量赋值以后该变量才会被创建。

等号 = 用来给变量赋值。

等号 = 运算符左边是一个变量名，等号 = 运算符右边是存储在变量中的值。例如：

In [ ]:
counter = 100 # 赋值整型变量
miles = 1000.0 # 浮点型
name = "John" # 字符串
 
print(counter)
print(miles)
print(name)

## 常用数据类型 Common Data Types

| 类型| 例子|
| -----  | ----- |
| 整数 | `-100` |
| 浮点数 | `3.1416` |
| 字符串 | `'hello'` |
| 列表 | `[1, 1.2, 'hello']` |
| 字典 | `{'dogs': 5, 'pigs': 3}`|
| 元组 | `('ring', 1000)`
| 集合 | `{1, 2, 3}`|
| 布尔型 | `True, False`|


In [3]:
import numpy as np

In [4]:
a=np.ones(3)
a

array([1., 1., 1.])

In [5]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [6]:
a/b

<ipython-input-6-aae42d317509>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b


array([inf, inf, inf])