# Python 数据类型

## 常用数据类型 Common Data Types

| 类型| 例子|
| -----  | ----- |
| 整数 | `-100` |
| 浮点数 | `3.1416` |
| 字符串 | `'hello'` |
| 列表 | `[1, 1.2, 'hello']` |
| 字典 | `{'dogs': 5, 'pigs': 3}`|
| 元组 | `('ring', 1000)`
| 集合 | `{1, 2, 3}`|
| 布尔型 | `True, False`|


In [3]:
import numpy as np

In [4]:
a=np.ones(3)
a

array([1., 1., 1.])

In [5]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [6]:
a/b

<ipython-input-6-aae42d317509>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b


array([inf, inf, inf])